name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "warm-retreat-01394" #Must be unique in Heroku
          heroku_email: "ar01094@surrey.ac.uk"
          healthcheck: "https://warm-retreat-01394.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
